[package]
name = "os"
version = "0.1.0"
edition = "2021"

# [lib]
# path = "src/kernel.rs"
# crate-type = ["staticlib"]
# test = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build-dependencies]
cc = "1.0"

[dependencies]
